openapi: 3.0.1
info:
  title: Mincuru Cars App
  version: 0.0.1
  contact:
    name: Wataru Sato
    url: 'https://awwa500.blogger.com'
    email: awwa500@gmail.com
  description: Mincuru Cars App API仕様
servers:
  - url: 'http://localhost/api/v1'
  - url: 'http://localhost:8080'
    description: Dev Server
  - url: 'http://localhost:3100'
    description: Stoplight Studio
  - url: 'http://localhost:4010'
    description: Stoplight Prism
paths:
  /users/login:
    post:
      description: ログイン
      operationId: post-users-login
      requestBody:
        description: 認証情報
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: hoge@example.com
                  format: email
                password:
                  type: string
                  format: password
                  example: password
              required:
                - email
                - password
        required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: tokentokentoken
                required:
                  - token
              example:
                token: access_token
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      summary: ''
      security: []
    parameters: []
  /users/logout:
    post:
      summary: ''
      operationId: post-users-logout
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      description: ログアウト
      parameters: []
  '/users/{id}':
    get:
      description: 指定したIDの'UserResponse'取得
      operationId: get-user
      parameters:
        - name: id
          in: path
          description: 対象AdminのID
          required: true
          style: simple
          explode: false
          schema:
            type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
              example:
                id: 666
                name: ほげ 太郎
                email: hoge_taro@example.com
                role: user
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      description: ユーザの削除
      operationId: delete-user
      parameters:
        - name: id
          in: path
          description: 対象AdminのID
          required: true
          style: simple
          explode: false
          schema:
            type: integer
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    patch:
      description: ユーザの更新
      operationId: patch-user
      parameters:
        - name: id
          in: path
          description: 対象AdminのID
          required: true
          style: simple
          explode: false
          schema:
            type: integer
      requestBody:
        description: 更新するAdmin情報
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  name: ほげ 太郎
              properties:
                name:
                  type: string
                  minLength: 1
                  example: ほげ 太郎
                email:
                  type: string
                  format: email
                  example: hoge@example.com
                role:
                  type: string
                  enum:
                    - user
                    - admin
                password:
                  type: string
                  format: password
        required: false
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
              example:
                id: 666
                name: ほげ 太郎
                email: hoge_taro@example.com
                role: user
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
  /users:
    get:
      summary: ''
      tags: []
      operationId: get-users
      parameters:
        - schema:
            type: string
            format: email
            example: hoge@example.com
          in: query
          name: email
          description: メールアドレス
          allowReserved: true
        - schema:
            type: string
            example: ほげ 太郎
          in: query
          name: name
          description: 名前
          allowReserved: true
        - schema:
            type: string
            enum:
              - user
              - admin
            example: user
          in: query
          name: role
          description: ロール
          allowReserved: true
      description: 条件にマッチしたユーザの一覧取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                x-examples:
                  example-1:
                    - id: 123
                      name: hoge fuga
                      email: hoge@example.com
                      role: user
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
              examples:
                example-1:
                  value:
                    - id: 1
                      name: ほげ 太郎1
                      email: hoge1@example.com
                      role: user
                    - id: 2
                      name: ほげ 太郎2
                      email: hoge2@example.com
                      role: admin
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security: []
    parameters: []
    post:
      summary: ''
      operationId: post-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      description: ユーザの追加
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  hoge: fuga
              properties:
                name:
                  type: string
                  minLength: 1
                  example: ほげ 太郎
                email:
                  type: string
                  format: email
                  example: hoge@example.com
                role:
                  type: string
                  enum:
                    - user
                    - admin
                  example: user
                password:
                  type: string
                  format: password
                  example: password
              required:
                - name
                - email
                - role
                - password
            examples: {}
        description: ''
components:
  schemas:
    UserResponse:
      type: object
      example:
        name: ''
        id: 0
        email: hoge@example.com
        role: user
      properties:
        id:
          type: integer
          example: 123
        name:
          type: string
          example: ほげ 太郎
        email:
          type: string
          format: email
          example: hoge@example.com
        role:
          type: string
          enum:
            - user
            - admin
          example: user
      required:
        - id
        - name
        - email
        - role
    ErrorResponse:
      required:
        - message
      type: object
      properties:
        message:
          type: string
      title: ''
    Users:
      title: Users
      type: array
      items:
        $ref: '#/components/schemas/UserResponse'
  responses: {}
  securitySchemes: {}
