package main

import (
	"database/sql"
	"testing"
	"time"
)

func seedTestCarCx5() {
	DB.Create(&Car{
		MakerName:       "マツダ",
		ModelName:       "CX-5",
		GradeName:       "25S Proactive",
		ModelCode:       sql.NullString{String: "6BA-KF5P"},
		Price:           sql.NullInt64{Int64: 3140500, Valid: true},
		Url:             sql.NullString{String: "https://www.mazda.co.jp/cars/cx-5/", Valid: true},
		ImageUrl:        sql.NullString{String: "https://upload.wikimedia.org/wikipedia/commons/8/85/2017_Mazda_CX-5_%28KF%29_Maxx_2WD_wagon_%282018-11-02%29_01.jpg", Valid: true},
		ModelChangeFull: sql.NullTime{Time: time.Date(2017, time.February, 1, 0, 0, 0, 0, time.Local), Valid: true},
		ModelChangeLast: sql.NullTime{Time: time.Date(2018, time.January, 1, 0, 0, 0, 0, time.Local), Valid: true},
		Body: Body{
			Length:           sql.NullInt64{Int64: 4545, Valid: true},
			Width:            sql.NullInt64{Int64: 1840, Valid: true},
			Height:           sql.NullInt64{Int64: 1690, Valid: true},
			WheelBase:        sql.NullInt64{Int64: 2700, Valid: true},
			TreadFront:       sql.NullInt64{Int64: 1595, Valid: true},
			TreadRear:        sql.NullInt64{Int64: 1595, Valid: true},
			MinRoadClearance: sql.NullInt64{Int64: 210, Valid: true},
			Weight:           sql.NullInt64{Int64: 1620, Valid: true},
		},
		Interior: Interior{
			Length: sql.NullInt64{Int64: 1890, Valid: true},
			Width:  sql.NullInt64{Int64: 1540, Valid: true},
			Height: sql.NullInt64{Int64: 1265, Valid: true},
			// LuggageCap: sql.NullInt64{Int64: 0, Valid: false},
			RidingCap: sql.NullInt64{Int64: 5, Valid: true},
		},
		Perf: Perf{
			MinTurningRadius: sql.NullFloat64{Float64: 5.5, Valid: true},
			FcrWltc:          sql.NullFloat64{Float64: 13.0, Valid: true},
			FcrWltcL:         sql.NullFloat64{Float64: 10.2, Valid: true},
			FcrWltcM:         sql.NullFloat64{Float64: 13.4, Valid: true},
			FcrWltcH:         sql.NullFloat64{Float64: 14.7, Valid: true},
			//FcrWltcExh:       sql.NullFloat64{Float64: 0, Valid: false},
			FcrJc08: sql.NullFloat64{Float64: 14.2, Valid: true},
			//MpcWltc:          sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltc:          sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcL:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcM:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcH:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcExh:       sql.NullFloat64{Float64: 0, Valid: false},
			//EcrJc08:          sql.NullFloat64{Float64: 0, Valid: false},
			//MpcJc08:          sql.NullFloat64{Float64: 0, Valid: false},
		},
		PowerTrain:  sql.NullString{String: (string)(ICE), Valid: true},
		DriveSystem: sql.NullString{String: (string)(AWD), Valid: true},
		Engine: Engine{
			Code:               sql.NullString{String: "PY-RPS", Valid: true},
			Type:               sql.NullString{String: "水冷直列4気筒DOHC16バルブ", Valid: true},
			Cylinders:          sql.NullInt64{Int64: 4, Valid: true},
			CylinderLayout:     sql.NullString{String: (string)(I), Valid: true},
			ValveSystem:        sql.NullString{String: (string)(DOHC), Valid: true},
			Displacement:       sql.NullFloat64{Float64: 2.488, Valid: true},
			Bore:               sql.NullFloat64{Float64: 89.0, Valid: true},
			Stroke:             sql.NullFloat64{Float64: 100.0, Valid: true},
			CompRatio:          sql.NullFloat64{Float64: 13.0, Valid: true},
			MaxOutput:          sql.NullFloat64{Float64: 138, Valid: true},
			MaxOutputLowerRpm:  sql.NullFloat64{Float64: 6000, Valid: true},
			MaxOutputHigherRpm: sql.NullFloat64{Float64: 6000, Valid: true},
			MaxTorque:          sql.NullFloat64{Float64: 250, Valid: true},
			MaxTorqueLowerRpm:  sql.NullFloat64{Float64: 4000, Valid: true},
			MaxTorqueHigherRpm: sql.NullFloat64{Float64: 4000, Valid: true},
			FuelSystem:         sql.NullString{String: "DI", Valid: true},
			FuelType:           sql.NullString{String: "無鉛レギュラーガソリン", Valid: true},
			FuelTankCap:        sql.NullInt64{Int64: 58, Valid: true},
		},
		// MotorX: Motor{},
		// MotorY: Motor{},
		// Battery: Battery{},
		Steering:        sql.NullString{String: "ラック&ピニオン式", Valid: true},
		SuspensionFront: sql.NullString{String: "マクファーソンストラット式", Valid: true},
		SuspensionRear:  sql.NullString{String: "マルチリンク式", Valid: true},
		BrakeFront:      sql.NullString{String: "ベンチレーテッドディスク", Valid: true},
		BrakeRear:       sql.NullString{String: "ディスク", Valid: true},
		TireFront: Tire{
			SectionWidth:  sql.NullInt64{Int64: 225, Valid: true},
			AspectRatio:   sql.NullInt64{Int64: 55, Valid: true},
			WheelDiameter: sql.NullInt64{Int64: 19, Valid: true},
		},
		TireRear: Tire{
			SectionWidth:  sql.NullInt64{Int64: 225, Valid: true},
			AspectRatio:   sql.NullInt64{Int64: 55, Valid: true},
			WheelDiameter: sql.NullInt64{Int64: 19, Valid: true},
		},
		Transmission: Transmission{
			Type:   sql.NullString{String: (string)(AT), Valid: true},
			Gears:  sql.NullInt64{Int64: 6, Valid: true},
			Ratio1: sql.NullFloat64{Float64: 3.552, Valid: true},
			Ratio2: sql.NullFloat64{Float64: 2.022, Valid: true},
			Ratio3: sql.NullFloat64{Float64: 1.452, Valid: true},
			Ratio4: sql.NullFloat64{Float64: 1.000, Valid: true},
			Ratio5: sql.NullFloat64{Float64: 0.708, Valid: true},
			Ratio6: sql.NullFloat64{Float64: 0.599, Valid: true},
			//Ratio7: ,
			//Ratio8: ,
			//Ratio9: ,
			//Ratio10: ,
			RatioRear:           sql.NullFloat64{Float64: 3.893, Valid: true},
			ReductionRatioFront: sql.NullFloat64{Float64: 4.624, Valid: true},
			ReductionRatioRear:  sql.NullFloat64{Float64: 2.928, Valid: true},
		},
		FuelEfficiency: sql.NullString{String: "ミラーサイクルエンジン アイドリングストップ機構 筒内直接噴射 可変バルブタイミング 気筒休止 充電制御 ロックアップ機構付トルクコンバーター 電動パワーステアリング", Valid: true},
	})
}

func seedTestCarCorollaTouring() {
	DB.Create(&Car{
		MakerName:       "トヨタ",
		ModelName:       "カローラツーリング",
		GradeName:       "HYBRID G-X E-Four",
		ModelCode:       sql.NullString{String: "6AA-ZWE214W-AWXNB"},
		Price:           sql.NullInt64{Int64: 2678500, Valid: true},
		Url:             sql.NullString{String: "https://toyota.jp/corollatouring/", Valid: true},
		ImageUrl:        sql.NullString{String: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Toyota_COROLLA_TOURING_HYBRID_W%C3%97B_2WD_%286AA-ZWE211W-AWXSB%29_front.jpg", Valid: true},
		ModelChangeFull: sql.NullTime{Time: time.Date(2019, time.September, 17, 0, 0, 0, 0, time.Local), Valid: true},
		ModelChangeLast: sql.NullTime{Time: time.Date(2021, time.November, 15, 0, 0, 0, 0, time.Local), Valid: true},
		Body: Body{
			Length:           sql.NullInt64{Int64: 4495, Valid: true},
			Width:            sql.NullInt64{Int64: 1745, Valid: true},
			Height:           sql.NullInt64{Int64: 1460, Valid: true},
			WheelBase:        sql.NullInt64{Int64: 2640, Valid: true},
			TreadFront:       sql.NullInt64{Int64: 1530, Valid: true},
			TreadRear:        sql.NullInt64{Int64: 1540, Valid: true},
			MinRoadClearance: sql.NullInt64{Int64: 130, Valid: true},
			Weight:           sql.NullInt64{Int64: 1410, Valid: true},
		},
		Interior: Interior{
			Length: sql.NullInt64{Int64: 1790, Valid: true},
			Width:  sql.NullInt64{Int64: 1510, Valid: true},
			Height: sql.NullInt64{Int64: 1160, Valid: true},
			// LuggageCap: sql.NullInt64{Int64: 0, Valid: false},
			RidingCap: sql.NullInt64{Int64: 5, Valid: true},
		},
		Perf: Perf{
			MinTurningRadius: sql.NullFloat64{Float64: 5.0, Valid: true},
			FcrWltc:          sql.NullFloat64{Float64: 26.8, Valid: true},
			FcrWltcL:         sql.NullFloat64{Float64: 25.1, Valid: true},
			FcrWltcM:         sql.NullFloat64{Float64: 28.1, Valid: true},
			FcrWltcH:         sql.NullFloat64{Float64: 26.8, Valid: true},
			//FcrWltcExh:       sql.NullFloat64{Float64: 0, Valid: false},
			FcrJc08: sql.NullFloat64{Float64: 31.0, Valid: true},
			//MpcWltc:          sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltc:          sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcL:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcM:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcH:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcExh:       sql.NullFloat64{Float64: 0, Valid: false},
			//EcrJc08:          sql.NullFloat64{Float64: 0, Valid: false},
			//MpcJc08:          sql.NullFloat64{Float64: 0, Valid: false},
		},
		PowerTrain:  sql.NullString{String: (string)(StrHV), Valid: true},
		DriveSystem: sql.NullString{String: (string)(AWD), Valid: true},
		Engine: Engine{
			Code:           sql.NullString{String: "2ZR-FXE", Valid: true},
			Type:           sql.NullString{String: "直列4気筒 DOHC 16バルブ VVT-i ミラーサイクル", Valid: true},
			Cylinders:      sql.NullInt64{Int64: 4, Valid: true},
			CylinderLayout: sql.NullString{String: (string)(I), Valid: true},
			ValveSystem:    sql.NullString{String: (string)(DOHC), Valid: true},
			Displacement:   sql.NullFloat64{Float64: 1.797, Valid: true},
			Bore:           sql.NullFloat64{Float64: 80.5, Valid: true},
			Stroke:         sql.NullFloat64{Float64: 88.3, Valid: true},
			//CompRatio:          sql.NullFloat64{Float64: 0, Valid: false},
			MaxOutput:          sql.NullFloat64{Float64: 72, Valid: true},
			MaxOutputLowerRpm:  sql.NullFloat64{Float64: 5200, Valid: true},
			MaxOutputHigherRpm: sql.NullFloat64{Float64: 5200, Valid: true},
			MaxTorque:          sql.NullFloat64{Float64: 142, Valid: true},
			MaxTorqueLowerRpm:  sql.NullFloat64{Float64: 3600, Valid: true},
			MaxTorqueHigherRpm: sql.NullFloat64{Float64: 3600, Valid: true},
			FuelSystem:         sql.NullString{String: "電子制御式燃料噴射装置(EFI)", Valid: true},
			FuelType:           sql.NullString{String: "無鉛レギュラーガソリン", Valid: true},
			FuelTankCap:        sql.NullInt64{Int64: 43, Valid: true},
		},
		MotorX: Motor{
			Code:    sql.NullString{String: "1NM", Valid: true},
			Type:    sql.NullString{String: "交流同期電動機", Valid: true},
			Purpose: sql.NullString{String: (string)(TRACTION_FRONT), Valid: true},
			//RatedOutput: ,
			MaxOutput: sql.NullFloat64{Float64: 53, Valid: true},
			//MaxOutputLowerRpm: ,
			//MaxOutputHigherRpm: ,
			MaxTorque: sql.NullFloat64{Float64: 163, Valid: true},
			//MaxTorqueLowerRpm: ,
			//MaxTorqueHigherRpm: ,
		},
		MotorY: Motor{
			Code:    sql.NullString{String: "1MM", Valid: true},
			Type:    sql.NullString{String: "交流同期電動機", Valid: true},
			Purpose: sql.NullString{String: (string)(TRACTION_REAR), Valid: true},
			//RatedOutput: ,
			MaxOutput: sql.NullFloat64{Float64: 5.3, Valid: true},
			//MaxOutputLowerRpm: ,
			//MaxOutputHigherRpm: ,
			MaxTorque: sql.NullFloat64{Float64: 55, Valid: true},
			//MaxTorqueLowerRpm: ,
			//MaxTorqueHigherRpm: ,
		},
		Battery: Battery{
			Type: sql.NullString{String: "ニッケル水素電池", Valid: true},
			//Quantity: ,
			//Voltage: ,
			Capacity: sql.NullFloat64{Float64: 6.5, Valid: true},
		},
		//Steering:        sql.NullString{String: "ラック&ピニオン式", Valid: true},
		SuspensionFront: sql.NullString{String: "マクファーソンストラット式コイルスプリング", Valid: true},
		SuspensionRear:  sql.NullString{String: "ダブルウィッシュボーン式コイルスプリング", Valid: true},
		BrakeFront:      sql.NullString{String: "ベンチレーテッドディスク", Valid: true},
		BrakeRear:       sql.NullString{String: "ディスク", Valid: true},
		TireFront: Tire{
			SectionWidth:  sql.NullInt64{Int64: 195, Valid: true},
			AspectRatio:   sql.NullInt64{Int64: 65, Valid: true},
			WheelDiameter: sql.NullInt64{Int64: 15, Valid: true},
		},
		TireRear: Tire{
			SectionWidth:  sql.NullInt64{Int64: 195, Valid: true},
			AspectRatio:   sql.NullInt64{Int64: 65, Valid: true},
			WheelDiameter: sql.NullInt64{Int64: 15, Valid: true},
		},
		Transmission: Transmission{
			Type: sql.NullString{String: (string)(PG), Valid: true},
			//Gears: sql.NullInt64{Int64: 6, Valid: true},
			//Ratio1: sql.NullFloat64{Float64: 3.552, Valid: true},
			//Ratio2: sql.NullFloat64{Float64: 2.022, Valid: true},
			//Ratio3: sql.NullFloat64{Float64: 1.452, Valid: true},
			//Ratio4: sql.NullFloat64{Float64: 1.000, Valid: true},
			//Ratio5: sql.NullFloat64{Float64: 0.708, Valid: true},
			//Ratio6: sql.NullFloat64{Float64: 0.599, Valid: true},
			//Ratio7: ,
			//Ratio8: ,
			//Ratio9: ,
			//Ratio10: ,
			//RatioRear:           sql.NullFloat64{Float64: 3.893, Valid: true},
			ReductionRatioFront: sql.NullFloat64{Float64: 2.834, Valid: true},
			ReductionRatioRear:  sql.NullFloat64{Float64: 10.487, Valid: true},
		},
		FuelEfficiency: sql.NullString{String: "ハイブリッドシステム アイドリングストップ装置 可変バルブタイミング 電動パワーステアリング 充電制御 電気式無段変速機", Valid: true},
	})
}

func seedTestCarNsx() {
	DB.Create(&Car{
		MakerName:       "ホンダ",
		ModelName:       "NSX",
		GradeName:       "Type S",
		ModelCode:       sql.NullString{String: "5AA-NC1"},
		Price:           sql.NullInt64{Int64: 27940000, Valid: true},
		Url:             sql.NullString{String: "https://www.honda.co.jp/NSX/types/", Valid: true},
		ImageUrl:        sql.NullString{String: "https://upload.wikimedia.org/wikipedia/commons/e/ea/2019_Honda_NSX_3.5_CAA-NC1_%2820190722%29_01.jpg", Valid: true},
		ModelChangeFull: sql.NullTime{Time: time.Date(2017, time.February, 27, 0, 0, 0, 0, time.Local), Valid: true},
		ModelChangeLast: sql.NullTime{Time: time.Date(2021, time.August, 30, 0, 0, 0, 0, time.Local), Valid: true},
		Body: Body{
			Length:           sql.NullInt64{Int64: 4535, Valid: true},
			Width:            sql.NullInt64{Int64: 1940, Valid: true},
			Height:           sql.NullInt64{Int64: 1215, Valid: true},
			WheelBase:        sql.NullInt64{Int64: 2630, Valid: true},
			TreadFront:       sql.NullInt64{Int64: 1665, Valid: true},
			TreadRear:        sql.NullInt64{Int64: 1635, Valid: true},
			MinRoadClearance: sql.NullInt64{Int64: 110, Valid: true},
			Weight:           sql.NullInt64{Int64: 1790, Valid: true},
		},
		Interior: Interior{
			// Length: sql.NullInt64{Int64: 1790, Valid: true},
			// Width:  sql.NullInt64{Int64: 1510, Valid: true},
			// Height: sql.NullInt64{Int64: 1160, Valid: true},
			// LuggageCap: sql.NullInt64{Int64: 0, Valid: false},
			RidingCap: sql.NullInt64{Int64: 2, Valid: true},
		},
		Perf: Perf{
			MinTurningRadius: sql.NullFloat64{Float64: 5.9, Valid: true},
			FcrWltc:          sql.NullFloat64{Float64: 10.6, Valid: true},
			FcrWltcL:         sql.NullFloat64{Float64: 7.8, Valid: true},
			FcrWltcM:         sql.NullFloat64{Float64: 12.1, Valid: true},
			FcrWltcH:         sql.NullFloat64{Float64: 11.4, Valid: true},
			//FcrWltcExh:       sql.NullFloat64{Float64: 0, Valid: false},
			// FcrJc08: sql.NullFloat64{Float64: 31.0, Valid: true},
			//MpcWltc:          sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltc:          sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcL:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcM:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcH:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcExh:       sql.NullFloat64{Float64: 0, Valid: false},
			//EcrJc08:          sql.NullFloat64{Float64: 0, Valid: false},
			//MpcJc08:          sql.NullFloat64{Float64: 0, Valid: false},
		},
		PowerTrain:  sql.NullString{String: (string)(MldHV), Valid: true},
		DriveSystem: sql.NullString{String: (string)(AWD), Valid: true},
		Engine: Engine{
			Code:               sql.NullString{String: "JNC", Valid: true},
			Type:               sql.NullString{String: "水冷V型6気筒縦置", Valid: true},
			Cylinders:          sql.NullInt64{Int64: 6, Valid: true},
			CylinderLayout:     sql.NullString{String: (string)(V), Valid: true},
			ValveSystem:        sql.NullString{String: (string)(DOHC), Valid: true},
			Displacement:       sql.NullFloat64{Float64: 3.492, Valid: true},
			Bore:               sql.NullFloat64{Float64: 91.0, Valid: true},
			Stroke:             sql.NullFloat64{Float64: 89.5, Valid: true},
			CompRatio:          sql.NullFloat64{Float64: 10.0, Valid: false},
			MaxOutput:          sql.NullFloat64{Float64: 389, Valid: true},
			MaxOutputLowerRpm:  sql.NullFloat64{Float64: 6500, Valid: true},
			MaxOutputHigherRpm: sql.NullFloat64{Float64: 6850, Valid: true},
			MaxTorque:          sql.NullFloat64{Float64: 600, Valid: true},
			MaxTorqueLowerRpm:  sql.NullFloat64{Float64: 2300, Valid: true},
			MaxTorqueHigherRpm: sql.NullFloat64{Float64: 6000, Valid: true},
			FuelSystem:         sql.NullString{String: "電子制御燃料噴射式(ホンダ PGM-FI)", Valid: true},
			FuelType:           sql.NullString{String: "無鉛プレミアムガソリン", Valid: true},
			FuelTankCap:        sql.NullInt64{Int64: 59, Valid: true},
		},
		MotorX: Motor{
			Code:    sql.NullString{String: "H3", Valid: true},
			Type:    sql.NullString{String: "交流同期電動機", Valid: true},
			Purpose: sql.NullString{String: (string)(TRACTION_FRONT), Valid: true},
			//RatedOutput: ,
			MaxOutput:          sql.NullFloat64{Float64: 27, Valid: true},
			MaxOutputLowerRpm:  sql.NullFloat64{Float64: 4000, Valid: true},
			MaxOutputHigherRpm: sql.NullFloat64{Float64: 4000, Valid: true},
			MaxTorque:          sql.NullFloat64{Float64: 73, Valid: true},
			MaxTorqueLowerRpm:  sql.NullFloat64{Float64: 0, Valid: true},
			MaxTorqueHigherRpm: sql.NullFloat64{Float64: 2000, Valid: true},
		},
		MotorY: Motor{
			Code:    sql.NullString{String: "H2", Valid: true},
			Type:    sql.NullString{String: "交流同期電動機", Valid: true},
			Purpose: sql.NullString{String: (string)(TRACTION_REAR), Valid: true},
			//RatedOutput: ,
			MaxOutput:          sql.NullFloat64{Float64: 35, Valid: true},
			MaxOutputLowerRpm:  sql.NullFloat64{Float64: 3000, Valid: true},
			MaxOutputHigherRpm: sql.NullFloat64{Float64: 3000, Valid: true},
			MaxTorque:          sql.NullFloat64{Float64: 148, Valid: true},
			MaxTorqueLowerRpm:  sql.NullFloat64{Float64: 500, Valid: true},
			MaxTorqueHigherRpm: sql.NullFloat64{Float64: 2000, Valid: true},
		},
		Battery: Battery{
			Type:     sql.NullString{String: "ニッケル水素電池", Valid: true},
			Quantity: sql.NullInt64{Int64: 72, Valid: true},
			//Voltage: ,
			// Capacity: sql.NullFloat64{Float64: 6.5, Valid: true},
		},
		Steering:        sql.NullString{String: "ラック&ピニオン式(電動パワーステアリング仕様)", Valid: true},
		SuspensionFront: sql.NullString{String: "ダブルウィッシュボーン式", Valid: true},
		SuspensionRear:  sql.NullString{String: "ウィッシュボーン式", Valid: true},
		BrakeFront:      sql.NullString{String: "油圧式ベンチレーテッドディスク", Valid: true},
		BrakeRear:       sql.NullString{String: "油圧式ベンチレーテッドディスク", Valid: true},
		TireFront: Tire{
			SectionWidth:  sql.NullInt64{Int64: 245, Valid: true},
			AspectRatio:   sql.NullInt64{Int64: 35, Valid: true},
			WheelDiameter: sql.NullInt64{Int64: 19, Valid: true},
		},
		TireRear: Tire{
			SectionWidth:  sql.NullInt64{Int64: 305, Valid: true},
			AspectRatio:   sql.NullInt64{Int64: 30, Valid: true},
			WheelDiameter: sql.NullInt64{Int64: 20, Valid: true},
		},
		Transmission: Transmission{
			Type:   sql.NullString{String: (string)(DCT), Valid: true},
			Gears:  sql.NullInt64{Int64: 9, Valid: true},
			Ratio1: sql.NullFloat64{Float64: 3.838, Valid: true},
			Ratio2: sql.NullFloat64{Float64: 2.433, Valid: true},
			Ratio3: sql.NullFloat64{Float64: 1.777, Valid: true},
			Ratio4: sql.NullFloat64{Float64: 1.427, Valid: true},
			Ratio5: sql.NullFloat64{Float64: 1.211, Valid: true},
			Ratio6: sql.NullFloat64{Float64: 1.038, Valid: true},
			Ratio7: sql.NullFloat64{Float64: 0.880, Valid: true},
			Ratio8: sql.NullFloat64{Float64: 0.747, Valid: true},
			Ratio9: sql.NullFloat64{Float64: 0.633, Valid: true},
			//Ratio10: ,
			RatioRear:           sql.NullFloat64{Float64: 2.394, Valid: true},
			ReductionRatioFront: sql.NullFloat64{Float64: 10.382, Valid: true},
			ReductionRatioRear:  sql.NullFloat64{Float64: 3.583, Valid: true},
		},
		FuelEfficiency: sql.NullString{String: "ハイブリッドシステム 直噴エンジン 可変バルブタイミング アイドリングストップ装置 電動パワーステアリング", Valid: true},
	})
}

func seedTestCarHondaE() {
	DB.Create(&Car{
		MakerName:       "ホンダ",
		ModelName:       "Honda e",
		GradeName:       "Honda e Advance",
		ModelCode:       sql.NullString{String: "ZAA-ZC7"},
		Price:           sql.NullInt64{Int64: 4950000, Valid: true},
		Url:             sql.NullString{String: "https://www.honda.co.jp/honda-e/", Valid: true},
		ImageUrl:        sql.NullString{String: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Honda_e_Advance_%28ZAA-ZC7%29_front.jpg", Valid: true},
		ModelChangeFull: sql.NullTime{Time: time.Date(2020, time.August, 27, 0, 0, 0, 0, time.Local), Valid: true},
		ModelChangeLast: sql.NullTime{Time: time.Date(2020, time.August, 27, 0, 0, 0, 0, time.Local), Valid: true},
		Body: Body{
			Length:           sql.NullInt64{Int64: 3895, Valid: true},
			Width:            sql.NullInt64{Int64: 1750, Valid: true},
			Height:           sql.NullInt64{Int64: 1510, Valid: true},
			WheelBase:        sql.NullInt64{Int64: 2530, Valid: true},
			TreadFront:       sql.NullInt64{Int64: 1510, Valid: true},
			TreadRear:        sql.NullInt64{Int64: 1505, Valid: true},
			MinRoadClearance: sql.NullInt64{Int64: 145, Valid: true},
			Weight:           sql.NullInt64{Int64: 1540, Valid: true},
		},
		Interior: Interior{
			Length: sql.NullInt64{Int64: 1845, Valid: true},
			Width:  sql.NullInt64{Int64: 1385, Valid: true},
			Height: sql.NullInt64{Int64: 1120, Valid: true},
			// LuggageCap: sql.NullInt64{Int64: 0, Valid: false},
			RidingCap: sql.NullInt64{Int64: 4, Valid: true},
		},
		Perf: Perf{
			MinTurningRadius: sql.NullFloat64{Float64: 4.3, Valid: true},
			//FcrWltc:          sql.NullFloat64{Float64: 26.8, Valid: true},
			//FcrWltcL:         sql.NullFloat64{Float64: 25.1, Valid: true},
			//FcrWltcM:         sql.NullFloat64{Float64: 28.1, Valid: true},
			//FcrWltcH:         sql.NullFloat64{Float64: 26.8, Valid: true},
			//FcrWltcExh:       sql.NullFloat64{Float64: 0, Valid: false},
			//FcrJc08: sql.NullFloat64{Float64: 31.0, Valid: true},
			MpcWltc:  sql.NullFloat64{Float64: 259, Valid: false},
			EcrWltc:  sql.NullFloat64{Float64: 138, Valid: false},
			EcrWltcL: sql.NullFloat64{Float64: 116, Valid: false},
			EcrWltcM: sql.NullFloat64{Float64: 130, Valid: false},
			EcrWltcH: sql.NullFloat64{Float64: 149, Valid: false},
			//EcrWltcExh:       sql.NullFloat64{Float64: 0, Valid: false},
			EcrJc08: sql.NullFloat64{Float64: 135, Valid: false},
			MpcJc08: sql.NullFloat64{Float64: 274, Valid: false},
		},
		PowerTrain:  sql.NullString{String: (string)(BEV), Valid: true},
		DriveSystem: sql.NullString{String: (string)(RR), Valid: true},
		// Engine: Engine{
		// 	Code:           sql.NullString{String: "2ZR-FXE", Valid: true},
		// 	Type:           sql.NullString{String: "直列4気筒 DOHC 16バルブ VVT-i ミラーサイクル", Valid: true},
		// 	Cylinders:      sql.NullInt64{Int64: 4, Valid: true},
		// 	CylinderLayout: sql.NullString{String: (string)(I), Valid: true},
		// 	ValveSystem:    sql.NullString{String: (string)(DOHC), Valid: true},
		// 	Displacement:   sql.NullFloat64{Float64: 1.797, Valid: true},
		// 	Bore:           sql.NullFloat64{Float64: 80.5, Valid: true},
		// 	Stroke:         sql.NullFloat64{Float64: 88.3, Valid: true},
		// 	CompRatio:          sql.NullFloat64{Float64: 0, Valid: false},
		// 	MaxOutput:          sql.NullFloat64{Float64: 72, Valid: true},
		// 	MaxOutputLowerRpm:  sql.NullFloat64{Float64: 5200, Valid: true},
		// 	MaxOutputHigherRpm: sql.NullFloat64{Float64: 5200, Valid: true},
		// 	MaxTorque:          sql.NullFloat64{Float64: 142, Valid: true},
		// 	MaxTorqueLowerRpm:  sql.NullFloat64{Float64: 3600, Valid: true},
		// 	MaxTorqueHigherRpm: sql.NullFloat64{Float64: 3600, Valid: true},
		// 	FuelSystem:         sql.NullString{String: "電子制御式燃料噴射装置(EFI)", Valid: true},
		// 	FuelType:           sql.NullString{String: "無鉛レギュラーガソリン", Valid: true},
		// 	FuelTankCap:        sql.NullInt64{Int64: 43, Valid: true},
		// },
		MotorX: Motor{
			Code:               sql.NullString{String: "MCF5", Valid: true},
			Type:               sql.NullString{String: "交流同期電動機", Valid: true},
			Purpose:            sql.NullString{String: (string)(TRACTION_REAR), Valid: true},
			RatedOutput:        sql.NullFloat64{Float64: 60, Valid: true},
			MaxOutput:          sql.NullFloat64{Float64: 113, Valid: true},
			MaxOutputLowerRpm:  sql.NullFloat64{Float64: 3497, Valid: true},
			MaxOutputHigherRpm: sql.NullFloat64{Float64: 10000, Valid: true},
			MaxTorque:          sql.NullFloat64{Float64: 315, Valid: true},
			MaxTorqueLowerRpm:  sql.NullFloat64{Float64: 0, Valid: true},
			MaxTorqueHigherRpm: sql.NullFloat64{Float64: 2000, Valid: true},
		},
		// MotorY: Motor{
		// 	Code:    sql.NullString{String: "1MM", Valid: true},
		// 	Type:    sql.NullString{String: "交流同期電動機", Valid: true},
		// 	Purpose: sql.NullString{String: (string)(TRACTION_REAR), Valid: true},
		// 	RatedOutput: ,
		// 	MaxOutput: sql.NullFloat64{Float64: 5.3, Valid: true},
		// 	MaxOutputLowerRpm: ,
		// 	MaxOutputHigherRpm: ,
		// 	MaxTorque: sql.NullFloat64{Float64: 55, Valid: true},
		// 	MaxTorqueLowerRpm: ,
		// 	MaxTorqueHigherRpm: ,
		// },
		Battery: Battery{
			Type:     sql.NullString{String: "リチウムイオン電池", Valid: true},
			Quantity: sql.NullInt64{Int64: 193, Valid: true},
			Voltage:  sql.NullFloat64{Float64: 3.7, Valid: true},
			Capacity: sql.NullFloat64{Float64: 50.0, Valid: true},
		},
		Steering:        sql.NullString{String: "ラック&ピニオン式", Valid: true},
		SuspensionFront: sql.NullString{String: "マクファーソン式", Valid: true},
		SuspensionRear:  sql.NullString{String: "マクファーソン式", Valid: true},
		BrakeFront:      sql.NullString{String: "油圧式ベンチレーテッドディスク", Valid: true},
		BrakeRear:       sql.NullString{String: "油圧式ディスク", Valid: true},
		TireFront: Tire{
			SectionWidth:  sql.NullInt64{Int64: 205, Valid: true},
			AspectRatio:   sql.NullInt64{Int64: 45, Valid: true},
			WheelDiameter: sql.NullInt64{Int64: 17, Valid: true},
		},
		TireRear: Tire{
			SectionWidth:  sql.NullInt64{Int64: 225, Valid: true},
			AspectRatio:   sql.NullInt64{Int64: 45, Valid: true},
			WheelDiameter: sql.NullInt64{Int64: 17, Valid: true},
		},
		Transmission: Transmission{
			// 	Type: sql.NullString{String: (string)(PG), Valid: true},
			// 	Gears: sql.NullInt64{Int64: 6, Valid: true},
			// 	Ratio1: sql.NullFloat64{Float64: 3.552, Valid: true},
			// 	Ratio2: sql.NullFloat64{Float64: 2.022, Valid: true},
			// 	Ratio3: sql.NullFloat64{Float64: 1.452, Valid: true},
			// 	Ratio4: sql.NullFloat64{Float64: 1.000, Valid: true},
			// 	Ratio5: sql.NullFloat64{Float64: 0.708, Valid: true},
			// 	Ratio6: sql.NullFloat64{Float64: 0.599, Valid: true},
			// 	Ratio7: ,
			// 	Ratio8: ,
			// 	Ratio9: ,
			// 	Ratio10: ,
			// 	RatioRear:           sql.NullFloat64{Float64: 3.893, Valid: true},
			ReductionRatioFront: sql.NullFloat64{Float64: 9.545, Valid: true},
			// 	ReductionRatioRear:  sql.NullFloat64{Float64: 10.487, Valid: true},
		},
		FuelEfficiency: sql.NullString{String: "電動パワーステアリング", Valid: true},
	})

}

func seedTestCarNote() {
	DB.Create(&Car{
		MakerName:       "日産",
		ModelName:       "ノート",
		GradeName:       "X FOUR",
		ModelCode:       sql.NullString{String: "6AA-SNE13"},
		Price:           sql.NullInt64{Int64: 2445300, Valid: true},
		Url:             sql.NullString{String: "https://www3.nissan.co.jp/vehicles/new/note.html", Valid: true},
		ImageUrl:        sql.NullString{String: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Nissan_Note_e-POWER_%28E13%29%2C_2021%2C_front-left.jpg", Valid: true},
		ModelChangeFull: sql.NullTime{Time: time.Date(2020, time.November, 24, 0, 0, 0, 0, time.Local), Valid: true},
		ModelChangeLast: sql.NullTime{Time: time.Date(2021, time.November, 4, 0, 0, 0, 0, time.Local), Valid: true},
		Body: Body{
			Length:           sql.NullInt64{Int64: 4045, Valid: true},
			Width:            sql.NullInt64{Int64: 1695, Valid: true},
			Height:           sql.NullInt64{Int64: 1520, Valid: true},
			WheelBase:        sql.NullInt64{Int64: 2580, Valid: true},
			TreadFront:       sql.NullInt64{Int64: 1490, Valid: true},
			TreadRear:        sql.NullInt64{Int64: 1490, Valid: true},
			MinRoadClearance: sql.NullInt64{Int64: 125, Valid: true},
			Weight:           sql.NullInt64{Int64: 1340, Valid: true},
		},
		Interior: Interior{
			Length: sql.NullInt64{Int64: 2030, Valid: true},
			Width:  sql.NullInt64{Int64: 1445, Valid: true},
			Height: sql.NullInt64{Int64: 1240, Valid: true},
			// LuggageCap: sql.NullInt64{Int64: 0, Valid: false},
			RidingCap: sql.NullInt64{Int64: 5, Valid: true},
		},
		Perf: Perf{
			MinTurningRadius: sql.NullFloat64{Float64: 4.9, Valid: true},
			FcrWltc:          sql.NullFloat64{Float64: 23.8, Valid: true},
			FcrWltcL:         sql.NullFloat64{Float64: 23.1, Valid: true},
			FcrWltcM:         sql.NullFloat64{Float64: 25.8, Valid: true},
			FcrWltcH:         sql.NullFloat64{Float64: 22.9, Valid: true},
			//FcrWltcExh:       sql.NullFloat64{Float64: 0, Valid: false},
			FcrJc08: sql.NullFloat64{Float64: 28.2, Valid: true},
			//MpcWltc:          sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltc:          sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcL:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcM:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcH:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcExh:       sql.NullFloat64{Float64: 0, Valid: false},
			//EcrJc08:          sql.NullFloat64{Float64: 0, Valid: false},
			//MpcJc08:          sql.NullFloat64{Float64: 0, Valid: false},
		},
		PowerTrain:  sql.NullString{String: (string)(SerHV), Valid: true},
		DriveSystem: sql.NullString{String: (string)(AWD), Valid: true},
		Engine: Engine{
			Code:               sql.NullString{String: "HR12DE", Valid: true},
			Type:               sql.NullString{String: "DOHC水冷直列3気筒", Valid: true},
			Cylinders:          sql.NullInt64{Int64: 3, Valid: true},
			CylinderLayout:     sql.NullString{String: (string)(I), Valid: true},
			ValveSystem:        sql.NullString{String: (string)(DOHC), Valid: true},
			Displacement:       sql.NullFloat64{Float64: 1.198, Valid: true},
			Bore:               sql.NullFloat64{Float64: 78.0, Valid: true},
			Stroke:             sql.NullFloat64{Float64: 83.6, Valid: true},
			CompRatio:          sql.NullFloat64{Float64: 12.0, Valid: false},
			MaxOutput:          sql.NullFloat64{Float64: 60, Valid: true},
			MaxOutputLowerRpm:  sql.NullFloat64{Float64: 6000, Valid: true},
			MaxOutputHigherRpm: sql.NullFloat64{Float64: 6000, Valid: true},
			MaxTorque:          sql.NullFloat64{Float64: 103, Valid: true},
			MaxTorqueLowerRpm:  sql.NullFloat64{Float64: 4800, Valid: true},
			MaxTorqueHigherRpm: sql.NullFloat64{Float64: 4800, Valid: true},
			FuelSystem:         sql.NullString{String: "ニッサンEGI(ECCS)電子制御燃料噴射装置", Valid: true},
			FuelType:           sql.NullString{String: "無鉛レギュラーガソリン", Valid: true},
			FuelTankCap:        sql.NullInt64{Int64: 36, Valid: true},
		},
		MotorX: Motor{
			Code:    sql.NullString{String: "EM47", Valid: true},
			Type:    sql.NullString{String: "交流同期電動機", Valid: true},
			Purpose: sql.NullString{String: (string)(GENERATOR), Valid: true},
			//RatedOutput: ,
			MaxOutput:          sql.NullFloat64{Float64: 85, Valid: true},
			MaxOutputLowerRpm:  sql.NullFloat64{Float64: 2900, Valid: true},
			MaxOutputHigherRpm: sql.NullFloat64{Float64: 10341, Valid: true},
			MaxTorque:          sql.NullFloat64{Float64: 280, Valid: true},
			MaxTorqueLowerRpm:  sql.NullFloat64{Float64: 0, Valid: true},
			MaxTorqueHigherRpm: sql.NullFloat64{Float64: 2900, Valid: true},
		},
		MotorY: Motor{
			Code:    sql.NullString{String: "MM48", Valid: true},
			Type:    sql.NullString{String: "交流同期電動機", Valid: true},
			Purpose: sql.NullString{String: (string)(TRACTION_REAR), Valid: true},
			// RatedOutput: ,
			MaxOutput:          sql.NullFloat64{Float64: 50, Valid: true},
			MaxOutputLowerRpm:  sql.NullFloat64{Float64: 4775, Valid: true},
			MaxOutputHigherRpm: sql.NullFloat64{Float64: 10024, Valid: true},
			MaxTorque:          sql.NullFloat64{Float64: 100, Valid: true},
			MaxTorqueLowerRpm:  sql.NullFloat64{Float64: 0, Valid: true},
			MaxTorqueHigherRpm: sql.NullFloat64{Float64: 4775, Valid: true},
		},
		Battery: Battery{
			Type: sql.NullString{String: "リチウムイオン電池", Valid: true},
			//Quantity: ,
			//Voltage: ,
			// Capacity: sql.NullFloat64{Float64: 6.5, Valid: true},
		},
		Steering:        sql.NullString{String: "ラック&ピニオン式", Valid: true},
		SuspensionFront: sql.NullString{String: "独立懸架ストラット式", Valid: true},
		SuspensionRear:  sql.NullString{String: "トーションビーム式", Valid: true},
		BrakeFront:      sql.NullString{String: "ベンチレーテッドディスク式", Valid: true},
		BrakeRear:       sql.NullString{String: "リーディングトレーリング式", Valid: true},
		TireFront: Tire{
			SectionWidth:  sql.NullInt64{Int64: 185, Valid: true},
			AspectRatio:   sql.NullInt64{Int64: 60, Valid: true},
			WheelDiameter: sql.NullInt64{Int64: 16, Valid: true},
		},
		TireRear: Tire{
			SectionWidth:  sql.NullInt64{Int64: 185, Valid: true},
			AspectRatio:   sql.NullInt64{Int64: 60, Valid: true},
			WheelDiameter: sql.NullInt64{Int64: 16, Valid: true},
		},
		Transmission: Transmission{
			// Type: sql.NullString{String: (string)(PG), Valid: true},
			//Gears: sql.NullInt64{Int64: 6, Valid: true},
			//Ratio1: sql.NullFloat64{Float64: 3.552, Valid: true},
			//Ratio2: sql.NullFloat64{Float64: 2.022, Valid: true},
			//Ratio3: sql.NullFloat64{Float64: 1.452, Valid: true},
			//Ratio4: sql.NullFloat64{Float64: 1.000, Valid: true},
			//Ratio5: sql.NullFloat64{Float64: 0.708, Valid: true},
			//Ratio6: sql.NullFloat64{Float64: 0.599, Valid: true},
			//Ratio7: ,
			//Ratio8: ,
			//Ratio9: ,
			//Ratio10: ,
			//RatioRear:           sql.NullFloat64{Float64: 3.893, Valid: true},
			ReductionRatioFront: sql.NullFloat64{Float64: 7.388, Valid: true},
			ReductionRatioRear:  sql.NullFloat64{Float64: 7.282, Valid: true},
		},
		FuelEfficiency: sql.NullString{String: "ハイブリッドシステム アイドリングストップ装置 可変バルブタイミング ミラーサイクル 電動パワーステアリング", Valid: true},
	})
}

func seedTestCarThree() {
	DB.Create(&Car{
		MakerName: "BMW",
		ModelName: "3シリーズツーリング",
		GradeName: "320d xDriveツーリング Standard",
		ModelCode: sql.NullString{String: "3DA-6L20"},
		Price:     sql.NullInt64{Int64: 6340000, Valid: true},
		Url:       sql.NullString{String: "https://www.bmw.co.jp/ja/all-models/3-series/touring/2019/bmw-3-series-touring-inspire.html", Valid: true},
		// ImageUrl:        sql.NullString{String: "", Valid: true},
		ModelChangeFull: sql.NullTime{Time: time.Date(2019, time.September, 26, 0, 0, 0, 0, time.Local), Valid: true},
		ModelChangeLast: sql.NullTime{Time: time.Date(2019, time.September, 26, 0, 0, 0, 0, time.Local), Valid: true},
		Body: Body{
			Length:           sql.NullInt64{Int64: 4715, Valid: true},
			Width:            sql.NullInt64{Int64: 1825, Valid: true},
			Height:           sql.NullInt64{Int64: 1475, Valid: true},
			WheelBase:        sql.NullInt64{Int64: 2850, Valid: true},
			TreadFront:       sql.NullInt64{Int64: 1575, Valid: true},
			TreadRear:        sql.NullInt64{Int64: 1590, Valid: true},
			MinRoadClearance: sql.NullInt64{Int64: 135, Valid: true},
			Weight:           sql.NullInt64{Int64: 1730, Valid: true},
		},
		Interior: Interior{
			// Length: sql.NullInt64{Int64: 1890, Valid: true},
			// Width:  sql.NullInt64{Int64: 1540, Valid: true},
			// Height: sql.NullInt64{Int64: 1265, Valid: true},
			LuggageCap: sql.NullInt64{Int64: 500, Valid: false},
			RidingCap:  sql.NullInt64{Int64: 5, Valid: true},
		},
		Perf: Perf{
			MinTurningRadius: sql.NullFloat64{Float64: 5.7, Valid: true},
			FcrWltc:          sql.NullFloat64{Float64: 15.6, Valid: true},
			FcrWltcL:         sql.NullFloat64{Float64: 12.6, Valid: true},
			FcrWltcM:         sql.NullFloat64{Float64: 14.9, Valid: true},
			FcrWltcH:         sql.NullFloat64{Float64: 18.0, Valid: true},
			//FcrWltcExh:       sql.NullFloat64{Float64: 0, Valid: false},
			FcrJc08: sql.NullFloat64{Float64: 19.6, Valid: true},
			//MpcWltc:          sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltc:          sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcL:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcM:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcH:         sql.NullFloat64{Float64: 0, Valid: false},
			//EcrWltcExh:       sql.NullFloat64{Float64: 0, Valid: false},
			//EcrJc08:          sql.NullFloat64{Float64: 0, Valid: false},
			//MpcJc08:          sql.NullFloat64{Float64: 0, Valid: false},
		},
		PowerTrain:  sql.NullString{String: (string)(ICE), Valid: true},
		DriveSystem: sql.NullString{String: (string)(AWD), Valid: true},
		Engine: Engine{
			Code:           sql.NullString{String: "B47D20B", Valid: true},
			Type:           sql.NullString{String: "直列4気筒DOHCディーゼル", Valid: true},
			Cylinders:      sql.NullInt64{Int64: 4, Valid: true},
			CylinderLayout: sql.NullString{String: (string)(I), Valid: true},
			ValveSystem:    sql.NullString{String: (string)(DOHC), Valid: true},
			Displacement:   sql.NullFloat64{Float64: 1.995, Valid: true},
			// Bore:               sql.NullFloat64{Float64: 140, Valid: true},
			// Stroke:             sql.NullFloat64{Float64: 100.0, Valid: true},
			// CompRatio:          sql.NullFloat64{Float64: 13.0, Valid: true},
			MaxOutput:          sql.NullFloat64{Float64: 140, Valid: true},
			MaxOutputLowerRpm:  sql.NullFloat64{Float64: 4000, Valid: true},
			MaxOutputHigherRpm: sql.NullFloat64{Float64: 4000, Valid: true},
			MaxTorque:          sql.NullFloat64{Float64: 400, Valid: true},
			MaxTorqueLowerRpm:  sql.NullFloat64{Float64: 1750, Valid: true},
			MaxTorqueHigherRpm: sql.NullFloat64{Float64: 2500, Valid: true},
			FuelSystem:         sql.NullString{String: "デジタル・ディーゼル・エレクトロニクス(DDE/電子燃料噴射装置)", Valid: true},
			FuelType:           sql.NullString{String: "軽油", Valid: true},
			FuelTankCap:        sql.NullInt64{Int64: 59, Valid: true},
		},
		// MotorX: Motor{},
		// MotorY: Motor{},
		// Battery: Battery{},
		Steering:        sql.NullString{String: "ラック&ピニオン式、単速感応式パワー・ステアリング", Valid: true},
		SuspensionFront: sql.NullString{String: "ダブル・ジョイント・スプリング・ストラット式、コイルスプリング", Valid: true},
		SuspensionRear:  sql.NullString{String: "5リンク式、コイル・スプリング", Valid: true},
		BrakeFront:      sql.NullString{String: "ベンチレーテッドディスク", Valid: true},
		BrakeRear:       sql.NullString{String: "ベンチレーテッドディスク", Valid: true},
		TireFront: Tire{
			SectionWidth:  sql.NullInt64{Int64: 225, Valid: true},
			AspectRatio:   sql.NullInt64{Int64: 50, Valid: true},
			WheelDiameter: sql.NullInt64{Int64: 17, Valid: true},
		},
		TireRear: Tire{
			SectionWidth:  sql.NullInt64{Int64: 225, Valid: true},
			AspectRatio:   sql.NullInt64{Int64: 50, Valid: true},
			WheelDiameter: sql.NullInt64{Int64: 17, Valid: true},
		},
		Transmission: Transmission{
			Type:   sql.NullString{String: (string)(AT), Valid: true},
			Gears:  sql.NullInt64{Int64: 8, Valid: true},
			Ratio1: sql.NullFloat64{Float64: 5.250, Valid: true},
			Ratio2: sql.NullFloat64{Float64: 3.360, Valid: true},
			Ratio3: sql.NullFloat64{Float64: 2.172, Valid: true},
			Ratio4: sql.NullFloat64{Float64: 1.720, Valid: true},
			Ratio5: sql.NullFloat64{Float64: 1.316, Valid: true},
			Ratio6: sql.NullFloat64{Float64: 1.000, Valid: true},
			Ratio7: sql.NullFloat64{Float64: 0.822, Valid: true},
			Ratio8: sql.NullFloat64{Float64: 0.640, Valid: true},
			//Ratio9: ,
			//Ratio10: ,
			RatioRear:           sql.NullFloat64{Float64: 3.712, Valid: true},
			ReductionRatioFront: sql.NullFloat64{Float64: 2.813, Valid: true},
			// ReductionRatioRear:  sql.NullFloat64{Float64: 2.813, Valid: true},
		},
		FuelEfficiency: sql.NullString{String: "筒内直接噴射 電子制御式燃料噴射 高圧噴射(コモンレール・ダイレクト・インジェクション・システム) 過給機(可変ジオメトリー・ターボチャージャー) 充電制御(ブレーキ・エネルギー回生システム) アイドリング・ストップ装置(エンジン・オート・スタート/ストップ) 電動パワーステアリング", Valid: true},
	})
}

func TestGetCars(t *testing.T) {
	DB.Exec("TRUNCATE TABLE cars")
	seedTestCarCx5()
	seedTestCarCorollaTouring()
	seedTestCarHondaE()
	seedTestCarNote()
	seedTestCarThree()
	seedTestCarNsx()
}
