/* tslint:disable */
/* eslint-disable */
/**
 * Mincuru Cars App
 * Mincuru Cars App API仕様
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: awwa500@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Battery
 */
export interface Battery {
    /**
     * 
     * @type {string}
     * @memberof Battery
     */
    'type'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Battery
     */
    'quantity'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Battery
     */
    'voltage'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Battery
     */
    'capacity'?: number | null;
}
/**
 * 
 * @export
 * @interface Body
 */
export interface Body {
    /**
     * 
     * @type {string}
     * @memberof Body
     */
    'type'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Body
     */
    'length'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Body
     */
    'width'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Body
     */
    'height'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Body
     */
    'wheel_base'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Body
     */
    'tread_front'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Body
     */
    'tread_rear'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Body
     */
    'min_road_clearance'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Body
     */
    'body_weight'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Body
     */
    'doors'?: number | null;
}
/**
 * 
 * @export
 * @interface Car
 */
export interface Car {
    /**
     * 
     * @type {number}
     * @memberof Car
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof Car
     */
    'is_del'?: number;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'maker_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'model_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'grade_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'model_code'?: string;
    /**
     * 
     * @type {number}
     * @memberof Car
     */
    'price'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'image_url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'model_change_full'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'model_change_last'?: string | null;
    /**
     * 
     * @type {Body}
     * @memberof Car
     */
    'body'?: Body;
    /**
     * 
     * @type {Interior}
     * @memberof Car
     */
    'interior'?: Interior;
    /**
     * 
     * @type {Performance}
     * @memberof Car
     */
    'performance'?: Performance;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'power_train'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'drive_system'?: string | null;
    /**
     * 
     * @type {Engine}
     * @memberof Car
     */
    'engine'?: Engine;
    /**
     * 
     * @type {Motor}
     * @memberof Car
     */
    'motor_x'?: Motor;
    /**
     * 
     * @type {Motor}
     * @memberof Car
     */
    'motor_y'?: Motor;
    /**
     * 
     * @type {Battery}
     * @memberof Car
     */
    'battery'?: Battery;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'steering'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'suspension_front'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'suspension_rear'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'brake_front'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'brake_rear'?: string | null;
    /**
     * 
     * @type {Tire}
     * @memberof Car
     */
    'tire_front'?: Tire;
    /**
     * 
     * @type {Tire}
     * @memberof Car
     */
    'tire_rear'?: Tire;
    /**
     * 
     * @type {Transmission}
     * @memberof Car
     */
    'transmission'?: Transmission;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    'fuel_efficiency'?: string | null;
}
/**
 * 
 * @export
 * @interface CodeResponse
 */
export interface CodeResponse {
    /**
     * 
     * @type {number}
     * @memberof CodeResponse
     */
    'code': number;
}
/**
 * 
 * @export
 * @interface Engine
 */
export interface Engine {
    /**
     * 
     * @type {string}
     * @memberof Engine
     */
    'code'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Engine
     */
    'type'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Engine
     */
    'cylinders'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Engine
     */
    'cylinder_layout'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Engine
     */
    'valve_system'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Engine
     */
    'displacement'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Engine
     */
    'bore'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Engine
     */
    'stroke'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Engine
     */
    'compression_ratio'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Engine
     */
    'max_output'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Engine
     */
    'max_output_lower_rpm'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Engine
     */
    'max_output_higher_rpm'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Engine
     */
    'max_torque'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Engine
     */
    'max_torque_lower_rpm'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Engine
     */
    'max_torque_higher_rpm'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Engine
     */
    'fuel_system'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Engine
     */
    'fuel_type'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Engine
     */
    'fuel_tank_cap'?: number | null;
}
/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface Id
 */
export interface Id {
    /**
     * 
     * @type {number}
     * @memberof Id
     */
    'id': number;
}
/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    'maker_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    'model_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    'grade_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    'model_code'?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    'price_lower'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    'price_higher'?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    'model_change_from'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    'model_change_to'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    'power_train'?: Array<InlineObjectPowerTrainEnum>;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineObjectPowerTrainEnum {
    Ice = 'ICE',
    StrHv = 'StrHV',
    MldHv = 'MldHV',
    SerHv = 'SerHV',
    Phev = 'PHEV',
    Bev = 'BEV',
    RexEv = 'RexEV',
    Fcev = 'FCEV'
}

/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'maker_name': string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'grade_name': string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'model_name': string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'model_code': string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    'price'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'image_url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'model_change_full'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'model_change_last'?: string | null;
}
/**
 * 
 * @export
 * @interface Interior
 */
export interface Interior {
    /**
     * 
     * @type {number}
     * @memberof Interior
     */
    'length'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Interior
     */
    'width'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Interior
     */
    'height'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Interior
     */
    'luggage_cap'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Interior
     */
    'riding_cap'?: number | null;
}
/**
 * 
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {
    /**
     * 
     * @type {string}
     * @memberof LoginRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof LoginRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface Motor
 */
export interface Motor {
    /**
     * 
     * @type {string}
     * @memberof Motor
     */
    'code'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Motor
     */
    'type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Motor
     */
    'purpose'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Motor
     */
    'rated_output'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Motor
     */
    'max_output'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Motor
     */
    'max_output_lower_rpm'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Motor
     */
    'max_output_higher_rpm'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Motor
     */
    'max_torque'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Motor
     */
    'max_torque_lower_rpm'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Motor
     */
    'max_torque_higher_rpm'?: number | null;
}
/**
 * 
 * @export
 * @interface PatchUserMeRequest
 */
export interface PatchUserMeRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchUserMeRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchUserMeRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchUserMeRequest
     */
    'password'?: string;
}
/**
 * 
 * @export
 * @interface PatchUserRequest
 */
export interface PatchUserRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchUserRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchUserRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchUserRequest
     */
    'role'?: PatchUserRequestRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchUserRequest
     */
    'password'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum PatchUserRequestRoleEnum {
    User = 'user',
    Admin = 'admin'
}

/**
 * 
 * @export
 * @interface Performance
 */
export interface Performance {
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'min_turning_radius'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'fcr_wltc'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'fcr_wltc_l'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'fcr_wltc_m'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'fcr_wltc_h'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'fcr_wltc_exh'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'fcr_jc08'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'mpc_wltc'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'ecr_wltc'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'ecr_wltc_l'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'ecr_wltc_m'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'ecr_wltc_h'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'ecr_wltc_exh'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'ecr_jc08'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Performance
     */
    'mpc_jc08'?: number | null;
}
/**
 * 
 * @export
 * @interface PostUserRequest
 */
export interface PostUserRequest {
    /**
     * 
     * @type {string}
     * @memberof PostUserRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof PostUserRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof PostUserRequest
     */
    'role': PostUserRequestRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof PostUserRequest
     */
    'password': string;
}

/**
    * @export
    * @enum {string}
    */
export enum PostUserRequestRoleEnum {
    User = 'user',
    Admin = 'admin'
}

/**
 * 
 * @export
 * @interface Tire
 */
export interface Tire {
    /**
     * 
     * @type {number}
     * @memberof Tire
     */
    'section_width'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Tire
     */
    'aspect_ratio'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Tire
     */
    'wheel_diameter'?: number | null;
}
/**
 * 
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
    /**
     * 
     * @type {number}
     * @memberof TokenResponse
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    'expire': string;
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    'token': string;
}
/**
 * 
 * @export
 * @interface Transmission
 */
export interface Transmission {
    /**
     * 
     * @type {string}
     * @memberof Transmission
     */
    'type'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'gears'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'ratio_1'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'ratio_2'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'ratio_3'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'ratio_4'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'ratio_5'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'ratio_6'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'ratio_7'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'ratio_8'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'ratio_9'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'ratio_10'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'ratio_rear'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'reduction_ratio_front'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Transmission
     */
    'reduction_ratio_rear'?: number | null;
}
/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'role': UserResponseRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'updated_at': string;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'is_del': number;
}

/**
    * @export
    * @enum {string}
    */
export enum UserResponseRoleEnum {
    User = 'user',
    Admin = 'admin'
}


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCarsId: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteCarsId', 'id', id)
            const localVarPath = `/cars/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 対象AdminのID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteUser', 'id', id)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Your GET endpoint
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCarsId: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getCarsId', 'id', id)
            const localVarPath = `/cars/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 対象AdminのID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getUser', 'id', id)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Your GET endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserMe: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [email] メールアドレス
         * @param {string} [name] 名前
         * @param {'user' | 'admin'} [role] ロール
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsers: async (email?: string, name?: string, role?: 'user' | 'admin', options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (role !== undefined) {
                localVarQueryParameter['role'] = role;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsersRefreshToken: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/refresh_token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {Car} [car] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchCarsId: async (id: string, car?: Car, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('patchCarsId', 'id', id)
            const localVarPath = `/cars/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(car, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 対象AdminのID
         * @param {PatchUserRequest} [patchUserRequest] 更新するAdmin情報
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchUser: async (id: number, patchUserRequest?: PatchUserRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('patchUser', 'id', id)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PatchUserMeRequest} [patchUserMeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchUserMe: async (patchUserMeRequest?: PatchUserMeRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchUserMeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Car} [car] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postCars: async (car?: Car, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cars`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(car, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {InlineObject} [inlineObject] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postCarsSearch: async (inlineObject?: InlineObject, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cars/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(inlineObject, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PostUserRequest} [postUserRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUsers: async (postUserRequest?: PostUserRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {LoginRequest} [loginRequest] 認証情報
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUsersLogin: async (loginRequest?: LoginRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUsersLogout: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCarsId(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCarsId(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id 対象AdminのID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUser(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUser(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Your GET endpoint
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCarsId(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Car>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCarsId(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id 対象AdminのID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUser(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUser(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Your GET endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserMe(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserMe(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} [email] メールアドレス
         * @param {string} [name] 名前
         * @param {'user' | 'admin'} [role] ロール
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUsers(email?: string, name?: string, role?: 'user' | 'admin', options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUsers(email, name, role, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUsersRefreshToken(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUsersRefreshToken(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {Car} [car] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchCarsId(id: string, car?: Car, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Id>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchCarsId(id, car, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id 対象AdminのID
         * @param {PatchUserRequest} [patchUserRequest] 更新するAdmin情報
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchUser(id: number, patchUserRequest?: PatchUserRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Id>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchUser(id, patchUserRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {PatchUserMeRequest} [patchUserMeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchUserMe(patchUserMeRequest?: PatchUserMeRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Id>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchUserMe(patchUserMeRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {Car} [car] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postCars(car?: Car, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Id>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postCars(car, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {InlineObject} [inlineObject] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postCarsSearch(inlineObject?: InlineObject, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<InlineResponse200>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postCarsSearch(inlineObject, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {PostUserRequest} [postUserRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUsers(postUserRequest?: PostUserRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Id>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postUsers(postUserRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {LoginRequest} [loginRequest] 認証情報
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUsersLogin(loginRequest?: LoginRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postUsersLogin(loginRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUsersLogout(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CodeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postUsersLogout(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCarsId(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteCarsId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 対象AdminのID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteUser(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Your GET endpoint
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCarsId(id: string, options?: any): AxiosPromise<Car> {
            return localVarFp.getCarsId(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 対象AdminのID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser(id: number, options?: any): AxiosPromise<UserResponse> {
            return localVarFp.getUser(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Your GET endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserMe(options?: any): AxiosPromise<UserResponse> {
            return localVarFp.getUserMe(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [email] メールアドレス
         * @param {string} [name] 名前
         * @param {'user' | 'admin'} [role] ロール
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsers(email?: string, name?: string, role?: 'user' | 'admin', options?: any): AxiosPromise<Array<UserResponse>> {
            return localVarFp.getUsers(email, name, role, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsersRefreshToken(options?: any): AxiosPromise<TokenResponse> {
            return localVarFp.getUsersRefreshToken(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {Car} [car] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchCarsId(id: string, car?: Car, options?: any): AxiosPromise<Id> {
            return localVarFp.patchCarsId(id, car, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 対象AdminのID
         * @param {PatchUserRequest} [patchUserRequest] 更新するAdmin情報
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchUser(id: number, patchUserRequest?: PatchUserRequest, options?: any): AxiosPromise<Id> {
            return localVarFp.patchUser(id, patchUserRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PatchUserMeRequest} [patchUserMeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchUserMe(patchUserMeRequest?: PatchUserMeRequest, options?: any): AxiosPromise<Id> {
            return localVarFp.patchUserMe(patchUserMeRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Car} [car] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postCars(car?: Car, options?: any): AxiosPromise<Id> {
            return localVarFp.postCars(car, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {InlineObject} [inlineObject] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postCarsSearch(inlineObject?: InlineObject, options?: any): AxiosPromise<Array<InlineResponse200>> {
            return localVarFp.postCarsSearch(inlineObject, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PostUserRequest} [postUserRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUsers(postUserRequest?: PostUserRequest, options?: any): AxiosPromise<Id> {
            return localVarFp.postUsers(postUserRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {LoginRequest} [loginRequest] 認証情報
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUsersLogin(loginRequest?: LoginRequest, options?: any): AxiosPromise<TokenResponse> {
            return localVarFp.postUsersLogin(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUsersLogout(options?: any): AxiosPromise<CodeResponse> {
            return localVarFp.postUsersLogout(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteCarsId(id: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteCarsId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 対象AdminのID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteUser(id: number, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteUser(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Your GET endpoint
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getCarsId(id: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getCarsId(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 対象AdminのID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getUser(id: number, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getUser(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Your GET endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getUserMe(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getUserMe(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [email] メールアドレス
     * @param {string} [name] 名前
     * @param {'user' | 'admin'} [role] ロール
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getUsers(email?: string, name?: string, role?: 'user' | 'admin', options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getUsers(email, name, role, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getUsersRefreshToken(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getUsersRefreshToken(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {Car} [car] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public patchCarsId(id: string, car?: Car, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).patchCarsId(id, car, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 対象AdminのID
     * @param {PatchUserRequest} [patchUserRequest] 更新するAdmin情報
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public patchUser(id: number, patchUserRequest?: PatchUserRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).patchUser(id, patchUserRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PatchUserMeRequest} [patchUserMeRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public patchUserMe(patchUserMeRequest?: PatchUserMeRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).patchUserMe(patchUserMeRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {Car} [car] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postCars(car?: Car, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postCars(car, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {InlineObject} [inlineObject] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postCarsSearch(inlineObject?: InlineObject, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postCarsSearch(inlineObject, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PostUserRequest} [postUserRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postUsers(postUserRequest?: PostUserRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postUsers(postUserRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {LoginRequest} [loginRequest] 認証情報
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postUsersLogin(loginRequest?: LoginRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postUsersLogin(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postUsersLogout(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postUsersLogout(options).then((request) => request(this.axios, this.basePath));
    }
}


