/* tslint:disable */
/* eslint-disable */
/**
 * Mincuru Cars App
 * Mincuru Cars App API仕様
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: awwa500@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AuthRequest,
    AuthRequestFromJSON,
    AuthRequestToJSON,
    AuthResponse,
    AuthResponseFromJSON,
    AuthResponseToJSON,
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PasswordRequest,
    PasswordRequestFromJSON,
    PasswordRequestToJSON,
    UserRequest,
    UserRequestFromJSON,
    UserRequestToJSON,
    UserResponse,
    UserResponseFromJSON,
    UserResponseToJSON,
} from '../models';

export interface DeleteUserRequest {
    id: number;
}

export interface GetUserRequest {
    id: number;
}

export interface GetUsersRequest {
    id?: number;
    email?: string;
}

export interface PatchUserRequest {
    id: number;
    userRequest?: UserRequest;
}

export interface PostUsersLoginRequest {
    authRequest?: AuthRequest;
}

export interface PutUsersPasswordRequest {
    id: number;
    passwordRequest?: PasswordRequest;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * ユーザの削除
     * @param {number} id 対象AdminのID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * ユーザの削除
     */
    deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 指定したIDの\'UserResponse\'取得
     * @param {number} id 対象AdminのID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getUserRaw(requestParameters: GetUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UserResponse>>;

    /**
     * 指定したIDの\'UserResponse\'取得
     */
    getUser(requestParameters: GetUserRequest, initOverrides?: RequestInit): Promise<UserResponse>;

    /**
     * 条件にマッチしたユーザの一覧取得
     * @param {number} [id] ユーザID
     * @param {string} [email] メールアドレス
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getUsersRaw(requestParameters: GetUsersRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Array<UserResponse>>>>;

    /**
     * 条件にマッチしたユーザの一覧取得
     */
    getUsers(requestParameters: GetUsersRequest, initOverrides?: RequestInit): Promise<Array<Array<UserResponse>>>;

    /**
     * ユーザの更新
     * @param {number} id 対象AdminのID
     * @param {UserRequest} [userRequest] 更新するAdmin情報
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    patchUserRaw(requestParameters: PatchUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UserResponse>>;

    /**
     * ユーザの更新
     */
    patchUser(requestParameters: PatchUserRequest, initOverrides?: RequestInit): Promise<UserResponse>;

    /**
     * ユーザの追加
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    postUsersRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<UserResponse>>;

    /**
     * ユーザの追加
     */
    postUsers(initOverrides?: RequestInit): Promise<UserResponse>;

    /**
     * ログイン
     * @param {AuthRequest} [authRequest] 認証情報
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    postUsersLoginRaw(requestParameters: PostUsersLoginRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AuthResponse>>;

    /**
     * ログイン
     */
    postUsersLogin(requestParameters: PostUsersLoginRequest, initOverrides?: RequestInit): Promise<AuthResponse>;

    /**
     * ログアウト
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    postUsersLogoutRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * ログアウト
     */
    postUsersLogout(initOverrides?: RequestInit): Promise<void>;

    /**
     * パスワードの更新
     * @param {number} id 対象AdminのID
     * @param {PasswordRequest} [passwordRequest] ハッシュ済みのパスワード
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    putUsersPasswordRaw(requestParameters: PutUsersPasswordRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * パスワードの更新
     */
    putUsersPassword(requestParameters: PutUsersPasswordRequest, initOverrides?: RequestInit): Promise<void>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     * ユーザの削除
     */
    async deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteUser.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ユーザの削除
     */
    async deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteUserRaw(requestParameters, initOverrides);
    }

    /**
     * 指定したIDの\'UserResponse\'取得
     */
    async getUserRaw(requestParameters: GetUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UserResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getUser.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * 指定したIDの\'UserResponse\'取得
     */
    async getUser(requestParameters: GetUserRequest, initOverrides?: RequestInit): Promise<UserResponse> {
        const response = await this.getUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 条件にマッチしたユーザの一覧取得
     */
    async getUsersRaw(requestParameters: GetUsersRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Array<UserResponse>>>> {
        const queryParameters: any = {};

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        if (requestParameters.email !== undefined) {
            queryParameters['email'] = requestParameters.email;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * 条件にマッチしたユーザの一覧取得
     */
    async getUsers(requestParameters: GetUsersRequest, initOverrides?: RequestInit): Promise<Array<Array<UserResponse>>> {
        const response = await this.getUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ユーザの更新
     */
    async patchUserRaw(requestParameters: PatchUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UserResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling patchUser.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserRequestToJSON(requestParameters.userRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * ユーザの更新
     */
    async patchUser(requestParameters: PatchUserRequest, initOverrides?: RequestInit): Promise<UserResponse> {
        const response = await this.patchUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ユーザの追加
     */
    async postUsersRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<UserResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * ユーザの追加
     */
    async postUsers(initOverrides?: RequestInit): Promise<UserResponse> {
        const response = await this.postUsersRaw(initOverrides);
        return await response.value();
    }

    /**
     * ログイン
     */
    async postUsersLoginRaw(requestParameters: PostUsersLoginRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AuthResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthRequestToJSON(requestParameters.authRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
    }

    /**
     * ログイン
     */
    async postUsersLogin(requestParameters: PostUsersLoginRequest, initOverrides?: RequestInit): Promise<AuthResponse> {
        const response = await this.postUsersLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ログアウト
     */
    async postUsersLogoutRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/logout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ログアウト
     */
    async postUsersLogout(initOverrides?: RequestInit): Promise<void> {
        await this.postUsersLogoutRaw(initOverrides);
    }

    /**
     * パスワードの更新
     */
    async putUsersPasswordRaw(requestParameters: PutUsersPasswordRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling putUsersPassword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}/password`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PasswordRequestToJSON(requestParameters.passwordRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * パスワードの更新
     */
    async putUsersPassword(requestParameters: PutUsersPasswordRequest, initOverrides?: RequestInit): Promise<void> {
        await this.putUsersPasswordRaw(requestParameters, initOverrides);
    }

}
