/* tslint:disable */
/* eslint-disable */
/**
 * Mincuru Cars App
 * Mincuru Cars App API仕様
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: awwa500@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CodeResponse,
    CodeResponseFromJSON,
    CodeResponseToJSON,
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    IdResponse,
    IdResponseFromJSON,
    IdResponseToJSON,
    LoginRequest,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    PatchUserRequest,
    PatchUserRequestFromJSON,
    PatchUserRequestToJSON,
    PostUserRequest,
    PostUserRequestFromJSON,
    PostUserRequestToJSON,
    TokenResponse,
    TokenResponseFromJSON,
    TokenResponseToJSON,
    UserResponse,
    UserResponseFromJSON,
    UserResponseToJSON,
} from '../models';

export interface DeleteUserRequest {
    id: number;
}

export interface GetUserRequest {
    id: number;
}

export interface GetUsersRequest {
    email?: string;
    name?: string;
    role?: GetUsersRoleEnum;
}

export interface PatchUserOperationRequest {
    id: number;
    patchUserRequest?: PatchUserRequest;
}

export interface PostUsersRequest {
    postUserRequest?: PostUserRequest;
}

export interface PostUsersLoginRequest {
    loginRequest?: LoginRequest;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * ユーザの削除
     * @param {number} id 対象AdminのID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * ユーザの削除
     */
    deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 指定したIDの\'UserResponse\'取得
     * @param {number} id 対象AdminのID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getUserRaw(requestParameters: GetUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UserResponse>>;

    /**
     * 指定したIDの\'UserResponse\'取得
     */
    getUser(requestParameters: GetUserRequest, initOverrides?: RequestInit): Promise<UserResponse>;

    /**
     * 条件にマッチしたユーザの一覧取得
     * @param {string} [email] メールアドレス
     * @param {string} [name] 名前
     * @param {'user' | 'admin'} [role] ロール
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getUsersRaw(requestParameters: GetUsersRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<UserResponse>>>;

    /**
     * 条件にマッチしたユーザの一覧取得
     */
    getUsers(requestParameters: GetUsersRequest, initOverrides?: RequestInit): Promise<Array<UserResponse>>;

    /**
     * トークン更新
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getUsersRefreshTokenRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<TokenResponse>>;

    /**
     * トークン更新
     */
    getUsersRefreshToken(initOverrides?: RequestInit): Promise<TokenResponse>;

    /**
     * ユーザの更新
     * @param {number} id 対象AdminのID
     * @param {PatchUserRequest} [patchUserRequest] 更新するAdmin情報
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    patchUserRaw(requestParameters: PatchUserOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<IdResponse>>;

    /**
     * ユーザの更新
     */
    patchUser(requestParameters: PatchUserOperationRequest, initOverrides?: RequestInit): Promise<IdResponse>;

    /**
     * ユーザの追加
     * @param {PostUserRequest} [postUserRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    postUsersRaw(requestParameters: PostUsersRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<IdResponse>>;

    /**
     * ユーザの追加
     */
    postUsers(requestParameters: PostUsersRequest, initOverrides?: RequestInit): Promise<IdResponse>;

    /**
     * ログイン
     * @param {LoginRequest} [loginRequest] 認証情報
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    postUsersLoginRaw(requestParameters: PostUsersLoginRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<TokenResponse>>;

    /**
     * ログイン
     */
    postUsersLogin(requestParameters: PostUsersLoginRequest, initOverrides?: RequestInit): Promise<TokenResponse>;

    /**
     * ログアウト
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    postUsersLogoutRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<CodeResponse>>;

    /**
     * ログアウト
     */
    postUsersLogout(initOverrides?: RequestInit): Promise<CodeResponse>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     * ユーザの削除
     */
    async deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteUser.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ユーザの削除
     */
    async deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteUserRaw(requestParameters, initOverrides);
    }

    /**
     * 指定したIDの\'UserResponse\'取得
     */
    async getUserRaw(requestParameters: GetUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UserResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getUser.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * 指定したIDの\'UserResponse\'取得
     */
    async getUser(requestParameters: GetUserRequest, initOverrides?: RequestInit): Promise<UserResponse> {
        const response = await this.getUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 条件にマッチしたユーザの一覧取得
     */
    async getUsersRaw(requestParameters: GetUsersRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<UserResponse>>> {
        const queryParameters: any = {};

        if (requestParameters.email !== undefined) {
            queryParameters['email'] = requestParameters.email;
        }

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        if (requestParameters.role !== undefined) {
            queryParameters['role'] = requestParameters.role;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserResponseFromJSON));
    }

    /**
     * 条件にマッチしたユーザの一覧取得
     */
    async getUsers(requestParameters: GetUsersRequest, initOverrides?: RequestInit): Promise<Array<UserResponse>> {
        const response = await this.getUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * トークン更新
     */
    async getUsersRefreshTokenRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<TokenResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/refresh_token`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * トークン更新
     */
    async getUsersRefreshToken(initOverrides?: RequestInit): Promise<TokenResponse> {
        const response = await this.getUsersRefreshTokenRaw(initOverrides);
        return await response.value();
    }

    /**
     * ユーザの更新
     */
    async patchUserRaw(requestParameters: PatchUserOperationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<IdResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling patchUser.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchUserRequestToJSON(requestParameters.patchUserRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IdResponseFromJSON(jsonValue));
    }

    /**
     * ユーザの更新
     */
    async patchUser(requestParameters: PatchUserOperationRequest, initOverrides?: RequestInit): Promise<IdResponse> {
        const response = await this.patchUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ユーザの追加
     */
    async postUsersRaw(requestParameters: PostUsersRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<IdResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostUserRequestToJSON(requestParameters.postUserRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IdResponseFromJSON(jsonValue));
    }

    /**
     * ユーザの追加
     */
    async postUsers(requestParameters: PostUsersRequest, initOverrides?: RequestInit): Promise<IdResponse> {
        const response = await this.postUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ログイン
     */
    async postUsersLoginRaw(requestParameters: PostUsersLoginRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<TokenResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters.loginRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * ログイン
     */
    async postUsersLogin(requestParameters: PostUsersLoginRequest, initOverrides?: RequestInit): Promise<TokenResponse> {
        const response = await this.postUsersLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ログアウト
     */
    async postUsersLogoutRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<CodeResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/logout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CodeResponseFromJSON(jsonValue));
    }

    /**
     * ログアウト
     */
    async postUsersLogout(initOverrides?: RequestInit): Promise<CodeResponse> {
        const response = await this.postUsersLogoutRaw(initOverrides);
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum GetUsersRoleEnum {
    User = 'user',
    Admin = 'admin'
}
