/* tslint:disable */
/* eslint-disable */
/**
 * Mincuru Cars App
 * Mincuru Cars App API仕様
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: awwa500@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordRequest
 */
export interface PasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof PasswordRequest
     */
    password: string;
}

export function PasswordRequestFromJSON(json: any): PasswordRequest {
    return PasswordRequestFromJSONTyped(json, false);
}

export function PasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': json['password'],
    };
}

export function PasswordRequestToJSON(value?: PasswordRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
    };
}

