/* tslint:disable */
/* eslint-disable */
/**
 * Mincuru Cars App
 * Mincuru Cars App API仕様
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: awwa500@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchUserRequest
 */
export interface PatchUserRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchUserRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchUserRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchUserRequest
     */
    role?: PatchUserRequestRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchUserRequest
     */
    password?: string;
}

/**
* @export
* @enum {string}
*/
export enum PatchUserRequestRoleEnum {
    User = 'user',
    Admin = 'admin'
}

export function PatchUserRequestFromJSON(json: any): PatchUserRequest {
    return PatchUserRequestFromJSONTyped(json, false);
}

export function PatchUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchUserRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'role': !exists(json, 'role') ? undefined : json['role'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function PatchUserRequestToJSON(value?: PatchUserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'role': value.role,
        'password': value.password,
    };
}

