/* tslint:disable */
/* eslint-disable */
/**
 * Mincuru Cars App
 * Mincuru Cars App API仕様
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: awwa500@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostUserRequest
 */
export interface PostUserRequest {
    /**
     * 
     * @type {string}
     * @memberof PostUserRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PostUserRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PostUserRequest
     */
    role: PostUserRequestRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof PostUserRequest
     */
    password: string;
}

/**
* @export
* @enum {string}
*/
export enum PostUserRequestRoleEnum {
    User = 'user',
    Admin = 'admin'
}

export function PostUserRequestFromJSON(json: any): PostUserRequest {
    return PostUserRequestFromJSONTyped(json, false);
}

export function PostUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostUserRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'role': json['role'],
        'password': json['password'],
    };
}

export function PostUserRequestToJSON(value?: PostUserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'role': value.role,
        'password': value.password,
    };
}

